declare const BABYLON: typeof import("babylonjs");

function material(scene: import("babylonjs").Scene, name: string, color: string, roughness = 0.9, alpha = 1): import("babylonjs").StandardMaterial {
  const mat = new BABYLON.StandardMaterial(name, scene);
  mat.diffuseColor = BABYLON.Color3.FromHexString(color);
  mat.specularColor = new BABYLON.Color3(0.08, 0.08, 0.08);
  mat.roughness = roughness;
  mat.alpha = alpha;
  if (alpha < 1) {
    mat.transparencyMode = BABYLON.Material.MATERIAL_ALPHABLEND;
    mat.needDepthPrePass = true;
  }
  return mat;
}

export function createMaterials(scene: import("babylonjs").Scene): Record<string, import("babylonjs").StandardMaterial> {
  return {
    grass: material(scene, "transparent-terrain-slope", "#8bcf6c", 0.9, 0.56),
    water: material(scene, "water", "#7eb9c0", 0.35),
    retaining: material(scene, "campus-retaining-wall", "#8d8271"),
    road: material(scene, "road", "#6f695d", 0.9, 0.82),
    pedestrian: material(scene, "pedestrian-path", "#e5d7a2", 0.9, 0.62),
    entranceWalk: material(scene, "entrance-direction-walk", "#d8c99d", 0.9, 0.45),
    entranceArrow: material(scene, "entrance-direction-arrow", "#2c6144"),
    plaza: material(scene, "plaza", "#d9cd9f"),
    parking: material(scene, "parking", "#cfc69e"),
    parkingLine: material(scene, "parking-line", "#f8f1d2"),
    scale: material(scene, "scale-ruler", "#173625"),
    scaleTick: material(scene, "scale-ruler-tick", "#f8f1d2"),
    wall: material(scene, "janggong-wall", "#d8d1c2"),
    sideWall: material(scene, "janggong-side-wall", "#c7b899"),
    pilheonWall: material(scene, "pilheon-wall", "#d6d2bf"),
    pilheonCore: material(scene, "pilheon-stair-core", "#b8b29c"),
    pilheonRoof: material(scene, "pilheon-roof", "#d9c28f"),
    manwooWall: material(scene, "manwoo-wall", "#b8b09d"),
    manwooSideWall: material(scene, "manwoo-side-wall", "#a79c83"),
    manwooRoof: material(scene, "manwoo-aged-roof", "#ded2a5"),
    manwooCorridor: material(scene, "manwoo-exterior-corridor", "#e5d6b4"),
    manwooStair: material(scene, "manwoo-exterior-stair", "#918a77"),
    manwooLounge: material(scene, "manwoo-lounge-glass", "#6ca3a8", 0.35),
    manwooHighlightWindow: material(scene, "manwoo-highlight-window", "#315e69", 0.35),
    shalomWall: material(scene, "shalom-wall", "#d9d0bd"),
    shalomPlinth: material(scene, "shalom-catacomb-plinth", "#8d8777"),
    shalomPorch: material(scene, "shalom-front-porch", "#c7b99c"),
    shalomOffice: material(scene, "shalom-office-4106", "#c8d2be"),
    shalomRoof: material(scene, "shalom-pitched-roof", "#7f5645"),
    shalomRidge: material(scene, "shalom-roof-ridge", "#5f4138"),
    shalomGlass: material(scene, "shalom-stained-glass", "#5c8fa4", 0.25),
    shalomCross: material(scene, "shalom-cross", "#e7ddbe"),
    immanuelWall: material(scene, "immanuel-student-union-wall", "#d3c8af"),
    immanuelBase: material(scene, "immanuel-basement-base", "#8f8876"),
    immanuelRoof: material(scene, "immanuel-flat-warm-roof", "#b99a72"),
    immanuelFoodGlass: material(scene, "immanuel-cafeteria-glass", "#85b6b4", 0.28),
    immanuelStore: material(scene, "immanuel-emart24-storefront", "#345a4b"),
    immanuelKitchen: material(scene, "immanuel-kitchen-service-band", "#a77f5e"),
    immanuelCanopy: material(scene, "immanuel-entry-canopy", "#e2d7b2"),
    immanuelClubGlass: material(scene, "immanuel-club-room-glass", "#315f67", 0.32),
    immanuelStudioGlass: material(scene, "immanuel-hbs-studio-glass", "#5d99a9", 0.24),
    immanuelNotice: material(scene, "immanuel-student-org-room", "#a7bf8c"),
    gyeongsamWall: material(scene, "gyeongsam-library-wall", "#c9c1ad"),
    gyeongsamSideWall: material(scene, "gyeongsam-book-stack-wall", "#b7ad97"),
    gyeongsamLobbyWall: material(scene, "gyeongsam-east-lobby-wall", "#d7d0bb"),
    gyeongsamRoof: material(scene, "gyeongsam-flat-roof", "#e3ddbf"),
    gyeongsamTrim: material(scene, "gyeongsam-horizontal-trim", "#8e8065"),
    gyeongsamGlass: material(scene, "gyeongsam-atrium-glass", "#7eaeb6", 0.25),
    gyeongsamTopGlass: material(scene, "gyeongsam-makerspace-glass", "#5f97a4", 0.26),
    gyeongsamLounge: material(scene, "gyeongsam-lounge-glass", "#91b08c", 0.3),
    gyeongsamWindow: material(scene, "gyeongsam-library-window", "#2f5863", 0.3),
    songamWall: material(scene, "songam-yusa-hall-wall", "#c9bfa8"),
    songamSideWall: material(scene, "songam-lab-wing-wall", "#b8ad94"),
    songamStageWall: material(scene, "songam-stage-back-wall", "#9d927b"),
    songamRoof: material(scene, "songam-flat-roof", "#eee6c5"),
    songamGlass: material(scene, "songam-hall-glass", "#79aab2", 0.26),
    songamWindow: material(scene, "songam-classroom-window", "#2f5863", 0.3),
    songamTrim: material(scene, "songam-front-trim", "#8d7d62"),
    sotongWall: material(scene, "sotong-professor-wall", "#c6bca5"),
    sotongCore: material(scene, "sotong-stair-core", "#938873"),
    sotongMuseum: material(scene, "sotong-museum-wing", "#b5c09d"),
    sotongRoof: material(scene, "sotong-flat-roof", "#e6dfc0"),
    sotongGlass: material(scene, "sotong-entry-glass", "#78a9b0", 0.26),
    sotongAccent: material(scene, "sotong-admin-accent", "#9ebc8f", 0.32),
    sotongWindow: material(scene, "sotong-office-window", "#315a64", 0.3),
    sotongTrim: material(scene, "sotong-horizontal-trim", "#8b7d63"),
    practiceWall: material(scene, "practice-workshop-wall", "#c9c0aa"),
    practiceSideWall: material(scene, "practice-startup-wing-wall", "#b8ae96"),
    practiceBase: material(scene, "practice-concrete-base", "#837c6b"),
    practiceRoof: material(scene, "practice-low-flat-roof", "#e6ddbd"),
    practiceGlass: material(scene, "practice-startup-glass", "#75a7ae", 0.26),
    practiceWindow: material(scene, "practice-lab-window", "#2f5964", 0.3),
    practiceDoor: material(scene, "practice-loading-door", "#496a65"),
    practiceTrim: material(scene, "practice-industrial-trim", "#81745d"),
    hanulWall: material(scene, "hanul-gymnasium-wall", "#d0c7b4"),
    hanulSideWall: material(scene, "hanul-side-wing-wall", "#b7ad98"),
    hanulBase: material(scene, "hanul-athletic-base", "#8b8575"),
    hanulRoof: material(scene, "hanul-wide-roof", "#e9e0bd"),
    hanulRoofRidge: material(scene, "hanul-raised-roof-ridge", "#c0a782"),
    hanulGlass: material(scene, "hanul-entry-glass", "#78a9b0", 0.26),
    hanulWindow: material(scene, "hanul-high-window", "#315a64", 0.3),
    hanulTrim: material(scene, "hanul-horizontal-trim", "#81745d"),
    seongbinWall: material(scene, "seongbin-new-dorm-wall", "#c6bb9f"),
    seongbinOldWall: material(scene, "seongbin-old-dorm-wall", "#b7aa91"),
    seongbinCore: material(scene, "seongbin-common-core", "#d3c7aa"),
    seongbinBase: material(scene, "seongbin-raised-base", "#837a69"),
    seongbinRoof: material(scene, "seongbin-red-brown-roof", "#9b6756"),
    seongbinGlass: material(scene, "seongbin-entry-glass", "#78a9b0", 0.26),
    seongbinWindow: material(scene, "seongbin-dorm-room-window", "#2f5964", 0.3),
    saeromWall: material(scene, "saerom-media-hall-wall", "#c8bea7"),
    saeromCafeWall: material(scene, "saerom-cafe-wall", "#d9c9a4"),
    saeromBase: material(scene, "saerom-park-base", "#867d6b"),
    saeromRoof: material(scene, "saerom-low-flat-roof", "#e8dfbd"),
    saeromTerrace: material(scene, "saerom-cafe-terrace", "#bca27b"),
    saeromGlass: material(scene, "saerom-cafe-glass", "#78a9b0", 0.26),
    saeromWindow: material(scene, "saerom-media-window", "#2f5964", 0.3),
    saeromAccent: material(scene, "saerom-cafe-sign-band", "#6a8f74"),
    haeoreumWall: material(scene, "haeoreum-third-lecture-wall", "#cbbfa7"),
    haeoreumSideWall: material(scene, "haeoreum-lab-wing-wall", "#b8ad96"),
    haeoreumCore: material(scene, "haeoreum-stair-core", "#938873"),
    haeoreumBase: material(scene, "haeoreum-raised-base", "#857c6b"),
    haeoreumRoof: material(scene, "haeoreum-flat-roof", "#e6ddbd"),
    haeoreumGlass: material(scene, "haeoreum-lounge-glass", "#78a9b0", 0.26),
    haeoreumWindow: material(scene, "haeoreum-class-window", "#315a64", 0.3),
    haeoreumService: material(scene, "haeoreum-post-health-band", "#93ae86"),
    joonhaWall: material(scene, "joonha-unification-wall", "#c9bea5"),
    joonhaSideWall: material(scene, "joonha-conference-wing-wall", "#b8ad96"),
    joonhaBase: material(scene, "joonha-memorial-base", "#837a68"),
    joonhaRoof: material(scene, "joonha-flat-roof", "#e6ddbd"),
    joonhaGlass: material(scene, "joonha-memorial-glass", "#78a9b0", 0.26),
    joonhaWindow: material(scene, "joonha-office-window", "#315a64", 0.3),
    joonhaMemorial: material(scene, "joonha-memory-room-panel", "#9f8160"),
    joonhaGarden: material(scene, "joonha-central-garden", "#6f9a63"),
    joonhaStone: material(scene, "joonha-dolbegae-stone", "#5f5b53"),
    neutbomWall: material(scene, "neutbom-modern-wall", "#d0c6b2"),
    neutbomCore: material(scene, "neutbom-elevator-core", "#a89f8c"),
    neutbomBase: material(scene, "neutbom-visible-b1-base", "#827969"),
    neutbomRoof: material(scene, "neutbom-clean-roof", "#e8dfbd"),
    neutbomGlass: material(scene, "neutbom-learning-glass", "#78a9b0", 0.26),
    neutbomStudioGlass: material(scene, "neutbom-studio-glass", "#5d99a9", 0.24),
    neutbomWindow: material(scene, "neutbom-class-window", "#315a64", 0.3),
    neutbomAccent: material(scene, "neutbom-media-accent", "#668f75"),
    neutbomBridge: material(scene, "neutbom-manwoo-bridge", "#c8bea7"),
    childcareWall: material(scene, "childcare-main-wall", "#d8ccb5"),
    childcareSideWall: material(scene, "childcare-auditorium-wall", "#c2b296"),
    childcareBase: material(scene, "childcare-safe-base", "#867c69"),
    childcareRoof: material(scene, "childcare-warm-roof", "#c78064"),
    childcareGlass: material(scene, "childcare-entry-glass", "#78a9b0", 0.26),
    childcareWindow: material(scene, "childcare-room-window", "#315a64", 0.3),
    childcareAccent: material(scene, "childcare-therapy-room-panel", "#a8bd8c"),
    childcareSand: material(scene, "childcare-sand-yard", "#dbc690"),
    childcareGarden: material(scene, "childcare-nature-yard", "#7fa568"),
    childcarePlay: material(scene, "childcare-play-equipment", "#d89b5f"),
    childcareSlide: material(scene, "childcare-slide", "#7eb9c0"),
    childcareFence: material(scene, "childcare-play-fence", "#f2e5bd"),
    roof: material(scene, "janggong-roof", "#b99673"),
    trim: material(scene, "janggong-floor-trim", "#8f8066"),
    column: material(scene, "janggong-entry-column", "#d7d0bf"),
    stone: material(scene, "janggong-stone", "#c9c2b2"),
    relief: material(scene, "janggong-relief-panel", "#7e6a4d"),
    bronze: material(scene, "janggong-bronze", "#9b7045"),
    glass: material(scene, "janggong-glass", "#8bb7bf", 0.25),
    window: material(scene, "janggong-window", "#375d68", 0.28),
    floorSlab: material(scene, "janggong-floor-plan-slab", "#e9dec2", 0.9, 0.72),
    corridor: material(scene, "janggong-plan-corridor", "#d8cda6"),
    roomLobby: material(scene, "janggong-room-lobby", "#79b6bd"),
    roomOffice: material(scene, "janggong-room-office", "#b7c98e"),
    roomRestroom: material(scene, "janggong-room-restroom", "#aebbd0"),
    roomMeeting: material(scene, "janggong-room-meeting", "#d19a71"),
    roomLecture: material(scene, "room-lecture", "#9fc7a3"),
    redRoof: material(scene, "red-roof", "#c6765f"),
    creamWall: material(scene, "cream-wall", "#e9e1cf")
  };
}
